# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95b725b10b44694065a23c1b89600f28b3f3492b6c09b278282841968e1ee6d02aaf8d00b68a093b2ac0c69f3f536b058a2b01e51c05208f68d7878f90407902

test:
  secret_key_base: cda411a60c6f9d99d0a1b278f05423786453be4923b3a855143d4798bde1fb8c19a790edc36a45f01f2bb2102211d4bafc8a2eae5d8357b0bb11734d3e204e60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
